name: Build & Release Wheel

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
      WHEEL_PKG: wheel_pkg

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup ROS 2 Jazzy apt repo
        run: |
          sudo apt update && sudo apt install -y software-properties-common curl gnupg lsb-release
          sudo add-apt-repository universe
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
            -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
            http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
            | sudo tee /etc/apt/sources.list.d/ros2-jazzy.list

      - name: Install ROS 2 Jazzy & Colcon
        run: |
          sudo apt update
          sudo apt install -y \
            ros-jazzy-ros-base \
            python3-colcon-common-extensions \
            ros-jazzy-ament-cmake-vendor-package \
            ros-jazzy-gz-sim-vendor \
            ros-jazzy-gz-math-vendor

      - name: Build math & sim with Colcon
        run: |
          source /opt/ros/jazzy/setup.bash && \
          colcon build --allow-overriding gz_sim_vendor gz_math_vendor --packages-select gz_sim_vendor gz_math_vendor

      - name: Prepare wheel package dir
        run: |
          cp install/gz_math_vendor/opt/gz_math_vendor/lib/python/gz/*.so \
             ${{ WHEEL_PKG }}/gz/.

      - name: Build wheel
        working-directory: ${{ WHEEL_PKG }}
        run: |
          python${{ env.PYTHON_VERSION }} -m pip install --upgrade build
          python${{ env.PYTHON_VERSION }} -m build --wheel

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Automated wheel for ${{ github.ref }}

      - name: Upload wheel
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            ${{ WHEEL_PKG }}/dist/*.whl
